name: Deploy Shababu Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to server
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: out/
        remote_path: /var/www/shababu/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
    
    - name: Deploy nginx config
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr
        path: nginx/
        remote_path: /tmp/nginx-configs/
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
    
    - name: Restart nginx
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 5m
        script: |
          sudo cp /tmp/nginx-configs/shababu.conf /etc/nginx/sites-available/
          sudo ln -sf /etc/nginx/sites-available/shababu.conf /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl restart nginx